### PR TITLE
Add backend and host args

### PR DESCRIPTION
**Pull request by Jomik**
Addresses #3  and #4

### CODE REVIEW

**Comment by laverdet** [comment]
This is a 400 line diff.

**Comment by Jomik** [comment]
Apologies, seems like my formatter kicked in. I will try to revert and recommit 👍

**Comment by Jomik** [comment]
Having some issues currently where this still does not solve my problem with running it in a docker container..

**Comment by Jomik** [comment]
I cannot seem to get this to work, sadly.
When authenticating, the it will properly redirect to steam, but sadly it sets `return_to` to `${internal_host}/api/auth/steam` instead of the `host`.

**Comment by Jomik** [comment]
Finally this is working. Depends on https://github.com/ScreepsMods/screepsmod-auth/pull/28

**Comment by Jomik** [comment]
@laverdet What is missing for this to be merged?

**Comment by laverdet** [comment]
Thanks! I think you'll run into caching issues if you ever use a different backend, so keep that in mind.

**Pull request merged**
